# **Arrays**

En Python, un **array** es una estructura de datos que organiza elementos (números, cadenas, etc.) en un formato similar a una matriz matemática, donde los elementos están indexados en posiciones específicas. A diferencia de las matrices matemáticas, el índice en un array comienza desde **0**, no desde 1.

Por ejemplo, para un array unidimensional:  
$$ a = [a_0, a_1, a_2, \dots, a_{n-1}] $$  
- Aquí, $(a_0)$ es el primer elemento y está en la posición 0.  
- El último elemento, $(a_{n-1})$, está en la posición $(n-1)$, donde $(n)$ es el tamaño del array.
- Usualmente los arrays unidemensionales se escriben en minusculas

Para un array bidimensional (o matriz):  
$$
A = \begin{bmatrix} 
a_{0,0} & a_{0,1} & a_{0,2} \\
a_{1,0} & a_{1,1} & a_{1,2} \\
a_{2,0} & a_{2,1} & a_{2,2}
\end{bmatrix}
$$
- Aquí, $(a_{0,0})$ representa el elemento en la primera fila y primera columna (índices `[0][0]`).
- Usualmente los arrays unidemensionales se escriben en minusculas


El uso de índices que empiezan desde 0 es una convención de Python y de muchos lenguajes de programación, lo que permite un acceso eficiente a los elementos.


In [1]:
#Importación de librerias
import numpy as np

In [12]:
#Creación de arrays
A = np.array([[2,4,3,7],[9,3,-1,2],[1,9,3,7],[6,6,3,7]])

print(A)

[[ 2  4  3  7]
 [ 9  3 -1  2]
 [ 1  9  3  7]
 [ 6  6  3  7]]


In [7]:
print(sum(A))

[18 22  8 23]


In [8]:
b=sum(sum(A))
print(b)

71


In [9]:
#La función suma proviene de la colección estandar de Python
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [11]:
b = np.sum(A)
print(b)

71


%whos enlista las variables en el workspace con información sobre el tipo y tamaño

In [12]:
%whos

Variable   Type       Data/Info
-------------------------------
A          ndarray    4x4: 16 elems, type `int64`, 128 bytes
b          int64      71
np         module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
numpy      module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>


In [13]:
np.who()

Name            Shape            Bytes            Type

_               4 x 4            128              int64
A               4 x 4            128              int64
_5 (_)          4 x 4            128              int64

Upper bound on total bytes  =       256


In [20]:
A

array([[ 2,  4,  3,  7],
       [ 9,  3, -1,  2],
       [ 1,  9,  3,  7],
       [ 6,  6,  3,  7]])

In [19]:
'''
A[2][1] accede al elemento de la tercera fila y segunda columna, que es 9.
'''

A[2,1]


9

In [21]:
# Reemplazo del termino A[2,1] por uno nuevo
A[2,1]= 30
A

array([[ 2,  4,  3,  7],
       [ 9,  3, -1,  2],
       [ 1, 30,  3,  7],
       [ 6,  6,  3,  7]])

In [24]:
#Remplazar varios elementos de la tercera fila
A[2,0:4]=[1, 3,  3, 5]

print(A)

[[ 2  4  3  7]
 [ 9  3 -1  2]
 [ 1  3  3  5]
 [ 6  6  3  7]]


## **Creación de arrays**


**`np.arange`** es una función en NumPy, una librería popular para cálculos numéricos en Python, que se utiliza para crear arrays con valores espaciados uniformemente dentro de un intervalo definido. La función sigue la notación de intervalo [start, stop), es decir, incluye el valor inicial (start) pero excluye el valor final (stop).

In [3]:
c=np.arange(0,10)

print(c)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
c = np.arange(1,10+0.5,0.5)
print(c)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


La función **`np.linspace`** se utiliza para crear arrays con valores igualmente espaciados dentro de un rango especificado. A diferencia de `np.arange`, **incluye ambos extremos del intervalo** por defecto, es decir, utiliza un intervalo cerrado **[start, stop]**.

In [11]:
c = np.linspace(0,10,11)

print(c)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [10]:
c = np.linspace(1,10,19)
print(c)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [16]:
B= np.array([[4,3,2,6],[7,8,6,4],[2,1,8,-9],[3,1,2,3]])
print('A =',A)
print('B =',B)

A = [[ 2  4  3  7]
 [ 9  3 -1  2]
 [ 1  9  3  7]
 [ 6  6  3  7]]
B = [[ 4  3  2  6]
 [ 7  8  6  4]
 [ 2  1  8 -9]
 [ 3  1  2  3]]


## **Multiplicación de matrices**

Esta operación sigue las reglas del álgebra matricial, donde el elemento $c_{ij}$ de la matriz resultante C es el producto escalar de la fila i de la primera matriz y la columna j de la segunda matriz.

* Requiere que las dimensiones sean compatibles, es decir, si $A$ es de tamaño $(m \times n)$, $B$ debe ser $(n \times p)$.
* Se utiliza para cálculos algebraicos, como transformaciones lineales o productos escalares de vectores.

In [27]:
'''
Se utiliza @ para la multiplicación matricial
'''

C= A@np.transpose(B) #np.transpose Transpone la matriz
print(C)

[[ 68  92 -31  37]
 [ 55  89  -5  34]
 [ 79 125 -28  39]
 [ 90 136 -21  51]]


In [28]:
'''
Otra manera de escribir la multiplicación matricial 
usando se usa np.matmul()
'''
C == np.matmul(A,np.transpose(B))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## **Multiplicación directa**

Esta operación multiplica cada elemento de una matriz por el elemento correspondiente de otra matriz, siguiendo la misma posición.

* Ambas matrices deben tener **dimensiones compatibles**(igual tamaño).

* Útil en aplicaciones que requieren operaciones punto a punto, como escalamiento de datos o transformaciones personalizadas:

In [32]:
'''
Usando *(operador de multiplicación directa):
'''

D=A*B
D

array([[  8,  12,   6,  42],
       [ 63,  24,  -6,   8],
       [  2,   9,  24, -63],
       [ 18,   6,   6,  21]])

In [34]:
'''
Otra manera de escribir la multiplicación directa 
es con np.multiply
'''
A*B==np.multiply(A,B)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])